"""create leads table

Revision ID: 1bbbed35dc39
Revises: 
Create Date: 2026-08-08 22:03:10.151281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bbbed35dc39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('newsletter_opt_in', sa.Boolean(), nullable=False),
    sa.Column('page', sa.String(length=512), nullable=True),
    sa.Column('attribution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('first_touch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ga_client_id', sa.String(length=64), nullable=True),
    sa.Column('ga_session_id', sa.String(length=64), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('spam_flagged', sa.Boolean(), nullable=False),
    sa.Column('spam_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('pipedrive_person_id', sa.Integer(), nullable=True),
    sa.Column('pipedrive_lead_id', sa.String(length=64), nullable=True),
    # CURRENT_TIMESTAMP is standard SQL — works on both Postgres and SQLite
    # (autogenerate froze Postgres's now(), which SQLite cannot evaluate)
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_sync_status'), 'leads', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_sync_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
